# the/directory/Gemfile
# frozen_string_literal: true

source "https://rubygems.org"

gem "ruby-lsp", "~> 0.17.4"
gem "debug"
gem "rubocop"
gem "rubocop-packaging"
gem "rubocop-performance"
gem "rubocop-rspec"
gem "rubocop-shopify"
gem "rubocop-thread_safety"

# Sorbet gems
gem "sorbet", group: :development
gem "sorbet-runtime"
gem "tapioca", require: false, group: :development  # For generating RBI files
