extends: default

rules:
  line-length:
    max: 120
  document-start: disable
  document-end: disable
  trailing-spaces: enable
  truthy:
    check-keys: false

schemas:
  - pattern: "**/trunk.{yml,yaml}"
    schema: "https://static.trunk.io/pub/trunk-yaml-schema.json"
  - pattern: ".github/workflows/*.{yml,yaml}"
    schema: "https://json.schemastore.org/github-workflow.json"
  - pattern: "**/*rubocop*.{yml,yaml}"
    schema: "https://raw.githubusercontent.com/rubocop/rubocop/master/config/default.yml"
  - pattern: "**/*standard*.{yml,yaml}"
    schema: "https://raw.githubusercontent.com/standardrb/standard/main/config/base.yml"
  - pattern: "**/*yamllint*.{yml,yaml}"
    schema: "https://json.schemastore.org/yamllint.json"
