source 'https://rubygems.org'

# should match .travis.yml
ruby '~> 3.2.2'

# rvm doesn't support the version range so we have to be more specific using the below magic comment: https://github.com/rvm/rvm/issues/3737
#ruby=3.2.2

# for sinatra-contrib
gem 'e2mmap'
gem 'backports', '~> 3.18'

gem "rake"

# daemons
gem 'sigdump'
gem 'json'
gem 'rgeo'
gem 'geocoder', '~> 1.6'
gem 'mixpanel_client', '~> 4.1', '>= 4.1.4'
gem 'mixpanel-ruby', '~> 2.2.0'
gem 'airbrake', '~> 11.0'
gem 'sd_notify', '~> 0.0.1'
# gem 'sucker_punch' # if we want to use airbrake async
gem 'phonie', '~> 2.0.2'
gem 'money'
gem 'monetize'
gem 'money-open-exchange-rates'

gem 'catch_json_parse_errors', git: 'https://github.com/pushd/catch_json_parse_errors', branch: 'dont_raise_if_accept_missing'

gem 'semantic', '~> 1.4.1'
gem 'imgix', '~> 1.2'
gem 'posix-spawn'
gem 'mini_exiftool', git: 'https://github.com/bcherry/mini_exiftool', branch: 'posix_spawn'
gem 'phashion', git: 'https://github.com/pushd/phashion', branch: 'master'
gem 'specific_install' # a hack to get phashion to actually be installed outside bundler
gem 'mini_magick'
gem 'magic', '~> 0.2.9'
gem 'rice'
gem 'hamcpp', git: 'https://github.com/pushd/hamcpp', branch: 'init'
gem 'oj'

gem 'algoliasearch'
gem 'business_time', '~> 0.13.0'
gem 'holidays', '~> 8.6'

gem 'simstring_pure', '~> 1.1'
gem 'gibbon', '~> 3.3', '>= 3.3.4'
gem 'klaviyo-api-sdk', '~> 11.1.0'

# SQL query comments with caller line
gem 'marginalia', '~> 1', '> 1.6', :require => false # this gem immediately connects to DB which breaks assets:precompile on deploy host https://github.com/basecamp/marginalia/issues/36

# for nokogiri force ruby combined with .bundle/config --use-system-libraries to use up-to-date system xml libs
# https://nokogiri.org/tutorials/installing_nokogiri.html#how-can-i-avoid-using-a-precompiled-native-gem
gem 'nokogiri', '~> 1.15.0', force_ruby_platform: true

gem 'premailer-rails', '~> 1.10.2'
gem 'mailchimp-api', '~> 2.0.6'
gem 'inky-rb', require: 'inky'

gem 'i18n-js'
gem 'rails-i18n'

gem 'valid_email2', '~> 2.1'

# version needed for Ruby 2.2
gem 'eventmachine', '~> 1.0.7'

gem 'stathat', '~> 0.1.7', git: 'https://github.com/pushd/stathat', branch: 'batch_async_points'
gem 'compass'
gem "sass-globbing", "~> 1.0.0"     # Not required for Rails 3.1+
gem "susy", "~> 1.0.9"

# admin
gem 'sinatra', '~> 1.4.7'
gem 'sinatra-contrib', '~> 1.4.7', :require => false
gem 'sinatra-cross_origin'
gem 'rack-ssl-enforcer'
gem 'sinatra-partial'
gem 'erubis'
gem 'rdiscount'

gem 'dalli', '~> 2.7'
gem 'rack-attack', '~> 6.7.0'

gem 'slack-ruby-client'

gem 'em-http-server', '~> 0.1.8'

gem 'googlecharts', '~> 1.6.12'
gem 'lograge', '~> 0.11.2'

gem 'rubystats', '~> 0.2.6'
gem 'walker_method', '~> 0.0.1'

# depend on major version of service-level gems as per https://github.com/aws/aws-sdk-ruby#supported-services
gem 'aws-sdk-ssm', '~> 1'
gem 'aws-sdk-cloudwatch', '~> 1'
gem 'aws-sdk-cloudwatchlogs', '~> 1'
gem 'aws-sdk-s3', '~> 1.141.0'
gem 'aws-sdk-s3control', '~> 1'
gem 'aws-sdk-sqs', '~> 1'
gem 'aws-sdk-sns', '~> 1'
gem 'aws-sdk-mediaconvert', '~> 1'
gem 'aws-sdk-cloudfront', '~> 1'
gem 'aws-sdk-ecs', '~> 1'
gem 'aws-sdk-ec2', '~> 1'
gem 'aws-sdk-autoscaling', '~> 1.69'
gem 'aws-sdk-iotdataplane', '~> 1'
gem 'aws-sdk-athena', '~> 1'

gem 'peddler', '~> 1.4.1'
gem 'amz_sp_api', git: 'https://github.com/bdelanghe/amz_sp_api', branch: 'just-inbound-upgrade'

gem 'netsuite', '~> 0.9.3'

gem 'buttercms-rails', '~> 1.2.1'
gem 'barby', '~> 0.6.9'

gem 'sass-rails'
gem 'compass-rails'
gem 'compass-susy-plugin'
gem "twitter-bootstrap-rails"

gem 'remote_syslog_logger', '~> 1.0.3'
gem 'rbtrace', '~> 0.4.8'

gem 'metabase', git: 'https://github.com/pushd/metabase-ruby', branch: 'old_deps'

gem 'google-cloud-bigquery'

gem 'alexa_verifier', '~> 1.0'
gem 'phonetic', '~> 1.2'
gem 'damerau-levenshtein', '~> 1.3', '>= 1.3.1'
gem 'google-cloud-dialogflow', '~> 0.2.2'

gem 'typhoeus', '~> 1.4.1'
gem 'memoist', '~> 0.16.0'

gem 'mobile_devices', '~> 0.3.0'
gem 'ios-devices', '~> 0.3.1'

gem 'fernet', '~> 2.3'

# Marketing site
gem 'font_assets', :git => 'https://github.com/mzsanford/font_assets.git', tag: 'v0.1.14'

gem 'zendesk_api', '~> 1.37'

gem 'lockup'

gem 'addressable', '~> 2.8'

gem 'shopify_api', git: 'https://github.com/pushd/shopify-api-ruby', branch: 'aura-9.4'
gem 'graphql', '~> 2.0.32' # for old shopify_api dependency CVE https://github.com/pushd/pushd-web/security/dependabot/103
gem 'active_shipping', '~> 1.9.2'
gem 'easypost'
gem 'diffy', '~> 3.4'
gem 'omniauth-google-oauth2', '~> 0.8.0'

gem 'responses_api_gem', git: 'https://github.com/pushd/responses-api-gem.git' # typeform

gem 'google-api-client'
gem 'contentful'
gem 'rich_text_renderer'
gem 'tzinfo-data', '~> 1.2022.3'
# security patches for subdependencies
gem 'ffi', '~> 1.9', '>= 1.9.25'
gem "loofah", ">= 2.2.3"
gem 'parallel_tests', '~> 3.3'

gem 'numpy', '~> 0.2.0'
gem 'ruby-zstds', '~> 1.0', '>= 1.0.4'

gem 'twilio-ruby'

group :rails do
  # FIXME:  this is merged into rails 5
  gem 'rails-api', '~> 0.4.1'

  source 'https://aura_home_inc_562:obQ3lzTKXoaRuoDm@gems.railslts.com' do
    gem 'rails', '~> 4.2', '>= 4.2.11.38'
    gem 'actionmailer',     require: false
    gem 'actionpack',       require: false
    gem 'activemodel',      require: false
    gem 'activerecord',     require: false
    gem 'activesupport',    require: false
    gem 'railties',         require: false
    gem 'actionview',       require: false
    gem 'railslts-version', require: false
    gem 'rack',             require: false
  end

  gem 'activeresource'

  # 0.0.2 but prevent infinite loop if there are more duplicate property_key values than batch_size by excluding seen ids,
  # and dont silently rescue missing property_key and handle nested attributes (fixed in Rails 6.0.3)
  gem 'ar-find-in-batches-with-order', :git => 'https://github.com/pushd/ar-find-in-batches-with-order.git'

  gem 'pg', '~> 0.21'

  gem 'activerecord-postgis-adapter', '~> 3.1', '>= 3.1.5'

  # FIXME:  this is pretty old and I think rails 5 supports it natively?
  gem 'active_model_serializers', '~> 0.8.1'

  # authentication and authorization
  gem 'devise', '~> 4'
  gem 'devise-i18n', '~> 1.9.4'
  gem 'cancan', '~> 1.6.10'

  # debug
  gem 'active_record_query_trace', '~> 1.5.4'

  # FIXME: this is the latest version and was released September 2019. It does not support ES6 syntax.
  gem 'uglifier', '~> 4.2.0'
end

group :test do
  gem "minitest", '~> 5.0'
  gem "minitest-reporters"
  gem 'mocha', '~> 1.0.0'
  gem "timecop", '~> 0.7.3'
  gem "rack-test"
  gem "webmock"
  gem 'test_after_commit'
  gem 'spy', '~> 1.0.3'
end

group :development do
  gem "thin"
  gem 'ruby-prof'
  gem "byebug", '~> 11.1.3'
  gem 'ruby-debug-ide', '~> 0.7.2'
  gem 'debase', '~> 0.2.4.1'
  gem 'gender_detector'
  gem 'bootsnap'
end

gem "spring", '~> 2.0.2', group: [:development, :test]
