source 'https://rubygems.org'

# Ruby version specification
ruby '~> 3.2.2'

# Linting and Formatting
gem 'standardrb', '1.49.0'
gem 'yamllint', '1.32.0'
gem 'rubocop', '1.57.1'

# Development tools
group :development do
  gem 'debug'
end
