source 'https://rubygems.org'

# Ruby version specification
ruby '~> 3.2.2'

# Linting and Formatting
gem 'standardrb', '~> 1.0.1'
gem 'yamllint', '~> 0.0.9'
gem 'rubocop', '~> 1.75.2'

# Development tools
group :development do
  gem 'debug'
end
