/**
 * This file was automatically generated by generate-types-from-schema.ts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the script to regenerate this file.
 */

/**
 * Defines the allowed value types for entries under the 'structure' key.
 */
export type StructureValue =
  | StructureEntry
  | DescriptionEntry
  | GlobalEntry
  | {}
  | string;

export interface Contracts {
  /**
   * Path to the JSON schema file for validation.
   */
  schema: string;
  quality: {
    /**
     * Linting configurations, keyed by linter name.
     */
    lint: {
      [k: string]: {
        /**
         * Dependencies for the linter, e.g., 'trunk'.
         */
        depends: string[];
        /**
         * Specific version of the linter.
         */
        version?: string;
      };
    };
  };
  external_files?: {
    setup?: string;
    roadmap?: string;
  };
  definitions?: {
    items?: {
      id: string;
      title: string;
      provides: string[];
      expects: string[];
      guarantees: string[];
    }[];
  };
  rules: {
    structure: {
      allow_empty_directory: boolean;
    };
  };
  /**
   * Repository structure contracts. Keys are file/directory paths.
   */
  structure: {
    [k: string]: StructureValue;
  };
}
export interface StructureEntry {
  type: "file" | "directory" | "symlink";
  purpose?: string;
  description?: string;
  depends_on?: string[];
  affects?: string[];
  ignores?: ("git" | "contract")[];
  ignore_patterns?: {
    [k: string]: string[];
  };
  /**
   * Reference to a schema definition (URL, path, or ref).
   */
  schema?: string;
  /**
   * Reference to a type definition file (URL, path, or ref).
   */
  types?: string;
}
export interface DescriptionEntry {
  description: string;
}
export interface GlobalEntry {
  description: string;
  ignore_patterns?: {
    [k: string]: string[];
  };
}
