// Source of truth for known Trunk linter IDs

export const KNOWN_LINTER_IDS = new Set([
  "ALL",
  "actionlint",
  "ansible-lint",
  "autopep8",
  "bandit",
  "black",
  "black-py",
  "brakeman",
  "buf-breaking",
  "buf-format",
  "buf-lint",
  "buildifier",
  "cfnlint",
  "clang-format",
  "clang-tidy",
  "clippy",
  "cue-fmt",
  "detekt",
  "detekt-explicit",
  "detekt-gradle",
  "dotenv-linter",
  "eslint",
  "flake8",
  "git-diff-check",
  "gitleaks",
  "gofmt",
  "goimports",
  "golangci-lint",
  "hadolint",
  "haml-lint",
  "include-what-you-use",
  "isort",
  "ktlint",
  "markdownlint",
  "mypy",
  "prettier",
  "pylint",
  "rubocop",
  "rubocop-fmt",
  "rufo",
  "rustfmt",
  "scalafmt",
  "semgrep",
  "shellcheck",
  "shfmt",
  "sql-formatter",
  "standardrb",
  "stylelint",
  "stylelint-fmt",
  "svgo",
  "taplo",
  "taplo-fmt",
  "terraform",
  "terraform-fmt",
  "terraform-validate",
  "tflint",
  "yamllint",
  "yapf",
]);

// Optional: Function to check if an ID is valid
export function isValidLinterId(id: string): boolean {
  return KNOWN_LINTER_IDS.has(id);
}
