#!/usr/bin/env -S deno run -A

/**
 * generate-types-from-schema.ts
 *
 * This script reads a JSON schema and generates corresponding TypeScript type definitions.
 * It uses the 'json-schema-to-typescript' library via Deno's Node compatibility layer.
 */

import { compile } from "npm:json-schema-to-typescript@14.0.0";
import { dirname, join } from "https://deno.land/std@0.219.0/path/mod.ts";
import { ensureDir } from "https://deno.land/std@0.219.0/fs/ensure_dir.ts";

// Paths
const SCHEMA_PATH = "./schemas/contracts-schema.json"; // Input JSON schema
const TYPES_OUTPUT_PATH = "./src/types/contracts.d.ts"; // Output TypeScript declaration file

/**
 * Generates TypeScript types from a JSON schema file.
 */
async function generateTypesFromSchema() {
  console.log(`Reading schema from ${SCHEMA_PATH}...`);
  let schemaJson;
  try {
    const schemaContent = await Deno.readTextFile(SCHEMA_PATH);
    schemaJson = JSON.parse(schemaContent);
    // Remove the $schema key as it can cause issues with some generators
    // and isn't needed for type generation itself.
    // Also remove title and description from root if they exist
    delete schemaJson.$schema;
    delete schemaJson.title;
    delete schemaJson.description;

    console.log("Schema read successfully.");
  } catch (error) {
    console.error(
      `Error reading or parsing schema file ${SCHEMA_PATH}:`,
      error,
    );
    Deno.exit(1);
  }

  console.log("Generating TypeScript types...");
  try {
    // Define a root type name for the schema
    const rootTypeName = "Contracts";

    const tsCode = await compile(schemaJson, rootTypeName, {
      bannerComment: `/**
 * This file was automatically generated by ${import.meta.url.split("/").pop()}.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the script to regenerate this file.
 */`,
      additionalProperties: false, // Adjust as needed based on schema intent
    });
    console.log("TypeScript types generated successfully.");

    // Ensure the output directory exists
    const outputDir = dirname(TYPES_OUTPUT_PATH);
    await ensureDir(outputDir);
    console.log(`Ensured output directory exists: ${outputDir}`);

    // Write the generated code to the output file
    await Deno.writeTextFile(TYPES_OUTPUT_PATH, tsCode);
    console.log(`TypeScript types written to ${TYPES_OUTPUT_PATH}`);
  } catch (error) {
    console.error("Error generating or writing TypeScript types:", error);
    Deno.exit(1);
  }
}

// --- Main Execution ---
if (import.meta.main) {
  await generateTypesFromSchema();
  console.log("Type generation process completed.");
}
