#!/usr/bin/env -S deno run --allow-read --allow-run=trunk --allow-write=src/generated/trunk_enums.ts --allow-env
// Script to generate TypeScript enums from dynamic lists.

import {
  getTrunkTools,
  getTrunkActions,
  getMiseActionAliases,
} from "../src/extractors/trunk_extractors.ts";
import { ensureDir } from "https://deno.land/std@0.224.0/fs/ensure_dir.ts";
import { join } from "https://deno.land/std@0.224.0/path/mod.ts";

const GENERATED_DIR = join(Deno.cwd(), "src", "generated");
const OUTPUT_FILE = join(GENERATED_DIR, "trunk_enums.ts");

/**
 * Converts a string to a valid TypeScript enum member name.
 * Handles kebab-case, replaces invalid characters.
 */
function toEnumMemberName(name: string): string {
  // Convert kebab-case to PascalCase (e.g., "foo-bar" -> "FooBar")
  // First, uppercase the first letter
  let memberName =
    name.charAt(0).toUpperCase() + name.slice(1).replace(/-([a-z])/g, g => g[1].toUpperCase());

  // Replace any characters not suitable for identifiers (allow letters, numbers, underscore)
  memberName = memberName.replace(/[^a-zA-Z0-9_]/g, "_");

  // Ensure it doesn't start with a number
  if (/^[0-9]/.test(memberName)) {
    memberName = "_" + memberName;
  }

  return memberName;
}

/**
 * Generates a TypeScript enum string from a list of values.
 */
function generateEnum(enumName: string, values: string[]): string {
  const members = values.map(value => `  ${toEnumMemberName(value)} = "${value}",`).join("\n");
  return `export enum ${enumName} {\n${members}\n}`;
}

async function main() {
  try {
    console.log("Generating enums...");

    // Ensure the output directory exists
    await ensureDir(GENERATED_DIR);

    // Get data from extractors
    const trunkTools = await getTrunkTools();
    // TODO: Get trunk actions
    const trunkActions = await getTrunkActions();
    // TODO: Get mise action aliases
    const miseActionAliases = await getMiseActionAliases();

    // Generate enum content
    const trunkToolsEnum = generateEnum("TrunkTool", trunkTools);
    // TODO: Generate trunk actions enum
    const trunkActionsEnum = generateEnum("TrunkAction", trunkActions);
    // TODO: Generate mise action aliases enum
    const miseActionAliasesEnum = generateEnum("MiseActionAlias", miseActionAliases);

    // Combine all enum strings
    const fileContent = [
      `// This file is generated by scripts/generate_enums.ts. Do not edit manually.`,
      `// Timestamp: ${new Date().toISOString()}`,
      trunkToolsEnum,
      // TODO: Add other enums here
      trunkActionsEnum,
      miseActionAliasesEnum,
    ].join("\n\n");

    // Write to file
    await Deno.writeTextFile(OUTPUT_FILE, fileContent);

    console.log(`Successfully generated enums in ${OUTPUT_FILE}`);
  } catch (error) {
    console.error("Error generating enums:", error);
    Deno.exit(1);
  }
}

if (import.meta.main) {
  main();
}
